### ISSUE TITLE
11. Risk and Technical Debt

### ISSUE THREAD

**Issue by Elias-Llera** [Arquisoft/radarin_en1a#16]
To assign

**Comment by sergady** [comment]
Definition of technical debt: is a concept in software development that reflects the implied cost of additional rework caused by choosing an easy (limited) solution now instead of using a better approach that would take longer.

Possible technical debts:
- Implement the gps with the google maps API
- Create a special interface or app for Android/IOS

**Comment by Elias-Llera** [comment]
Como documentar la sección: https://docs.arc42.org/section-11/

**Comment by JairoGC-1812** [comment]
After a thorough team review we consider this matter completed
